name: Build
on: workflow_dispatch
jobs:
  Build:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout breakpad
        uses: actions/checkout@v4
        with:
          repository: google/breakpad
          ref: chrome_99
      - name: Checkout lss
        run: |
          git clone https://chromium.googlesource.com/linux-syscall-support src/third_party/lss
          cd src/third_party/lss
          git checkout e1e7b0ad8ee99a875b272c8e33e308472e897660
      - name: Build
        run: |
          chmod +x ./configure
          ./configure --prefix=`pwd`/out
          make
          make install
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./out/bin
          tar -czvf breakpad.${{ github.ref_name }}.tar.gz -C ./out/bin .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: breakpad.${{ github.ref_name }}.tar.gz